### ISSUE TITLE
AFL 

### ISSUE THREAD

**Issue by FNCGROUP** [jetdario/hrms#10]
- NEED E separate, per branch na lang instead sa per corporation @ PDF report - ok as of 4/15/16 payroll.
- like sa sanmar resorts e separate ang chalet sa arwana
- p export to excell na lang pra sa pag generate per corporation, pki butangan na lang branches.

**Comment by jetdario** [comment]
@FNCGROUP : ready for review.

**Comment by jetdario** [comment]
@FNCGROUP : paki review sang report nga  ni kay dugay ko na ni na tapos

**Comment by FNCGROUP** [comment]
- SIR pa export to excell na lang kulang.

**Comment by jetdario** [comment]
ok

**Comment by jetdario** [comment]
@FNCGROUP : ready for review

**Comment by FNCGROUP** [comment]
OK 6/21/2016
