### ISSUE TITLE
sss loan report as of march 2016

### ISSUE THREAD

**Issue by FNCGROUP** [jetdario/hrms#11]
- wala branch name sa pdf report all affiliates. ok as of 4/15/16 payroll
  -pa add sa excell report. same sa remittances.
  -Sa big italian serving - CDO wala series # ang PDF report - ok as of 4/15/16 payroll

**Comment by jetdario** [comment]
@FNCGROUP : ready for review

**Comment by jetdario** [comment]
@FNCGROUP : ready for review
