### ISSUE TITLE
HDMF LOAN PDF Report as of march 2016

### ISSUE THREAD

**Issue by FNCGROUP** [jetdario/hrms#13]
- wala branch name all affiliates - ok as of 4/15/16 payroll
  **\- pa export to excel.**
  -wala series # ang PDF report sa Big Italian Serving - CDO  - ok as of 4/15/16 payroll
  -dapat full name ang m reflect sa report for confirmation s actual reporting (all branches) - ok as of 4/15/16 payroll
  -wala series # all branch sa dulcinea - ok as of 4/15/16 payroll

**Comment by jetdario** [comment]
@FNCGROUP : ano ang series #?

**Comment by jetdario** [comment]
@FNCGROUP : ready for review.

**Comment by jetdario** [comment]
@FNCGROUP : ready for review
