### ISSUE TITLE
Payroll Register PDF Report as of March 2016

### ISSUE THREAD

**Issue by FNCGROUP** [jetdario/hrms#14]
- ang branch name indi fullname ang naga guwa. dapat full branch name ang ma reflect sa report.
 like sm city cebu foodhall ang naga reflect  sm city cebu only. which is my ara nata sa favorite pizzas branch nga sm city cebu. - ok as of 4/15/16 payroll
- all on call PDF report kulang ang g reflect na name. ok as of 4/15/16 payroll

**Comment by jetdario** [comment]
@FNCGROUP : ready for review.
