### ISSUE TITLE
HDMF REMITTANCE REPORT PDF AS OF MARCH 2016

### ISSUE THREAD

**Issue by FNCGROUP** [jetdario/hrms#16]
- dapat full name ang m reflect sa report for confirmation s actual reporting (all branches) - ok as of 4/15/16 payroll

**Comment by jetdario** [comment]
@FNCGROUP : ready for review.

**Comment by FNCGROUP** [comment]
- PDF REPORT KANG BISI AURA ANG G GWA FISI MARKET, pero ok man ang mga list sang employees.

**Comment by jetdario** [comment]
@FNCGROUP : ready for review

**Comment by FNCGROUP** [comment]
no changes

**Comment by FNCGROUP** [comment]
-WALA AMOUNT ANG employee share sa excel report

**Comment by FNCGROUP** [comment]
ok 2-15-17

**Comment by FNCGROUP** [comment]
- lain ang branch sa pdf report.
- dulcinea robinsons magnolia gna generate pero greenbelt g gwa sa report.
- same sa sss, phic, hdmf pdf report

**Comment by FNCGROUP** [comment]
- pa add birthday sa gina generate nga excell report sa sss, phic, hdmf, tin excell report
