### ISSUE TITLE
PHIC REMITTANCES PDF REPORT AS OF MARCH 2016

### ISSUE THREAD

**Issue by FNCGROUP** [jetdario/hrms#17]
- dapat full name ang m reflect sa report for confirmation s actual reporting (all branches)

**Comment by jetdario** [comment]
ano namin mo nga fullname? please provide example.

**Comment by FNCGROUP** [comment]
-sa Fastfood naga reflect sa PDF report sm cebu lang, dapat sm cebu foodhall. tpus sm iloilo dapat sm iloilo foodhall, ang mga laba ngalan sang branch wla g reflect tanan.

**Comment by jetdario** [comment]
@FNCGROUP : ready for review.

**Comment by FNCGROUP** [comment]
- as of 4/9/16  for  4/15/16 payroll wala changes.

**Comment by FNCGROUP** [comment]
-AS OF MAY 20, 2016  ANG generatemckinley pero ang g gwa sa PDF report sm aura

**Comment by FNCGROUP** [comment]
-phic report ni BISI DASMA ang from other branch wala g reflect sa excell report pero sa pdf ara.

**Comment by FNCGROUP** [comment]
-sala ang branch name sa pdf report pag my interbranch. like eastwood dapat pero g reflect sa pdf ayala tower 1.

**Comment by FNCGROUP** [comment]
ok 2-15-17
