### ISSUE TITLE
WORKING Holiday Special

### ISSUE THREAD

**Issue by FNCGROUP** [jetdario/hrms#31]
- for Daily as of July 06, 2016 checking
       if my late or undertime, dapat my ma reflect nga late or undertime sa regular late/undertime equivalent of it.Then my late/undertime sa holiday late/undertime equivalent of it.
      paki net ang holiday pay sang late/undertime during holiday. kay indi ma tally pag gin compute ang excell, my naka hide nga deduction which is ang late/undertime during holiday.

**Comment by jetdario** [comment]
pero sakto ang computation?

On Wednesday, 6 July 2016, FNCGROUP <notifications@github.com> wrote:

>
>    - for Daily as of July 06, 2016 checking if my late or undertime,
>    dapat my ma reflect nga late or undertime sa regular late/undertime
>    equivalent of it.Then my late/undertime sa holiday late/undertime
>    equivalent of it. paki net ang holiday pay sang late/undertime during
>    holiday. kay indi ma tally pag gin compute ang excell, my naka hide nga
>    deduction which is ang late/undertime during holiday.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jetdario/hrms/issues/31>, or mute the thread
> <https://github.com/notifications/unsubscribe/AGpj3ZjvhDdqhVLBEya43Yg-yYwEosk1ks5qSx_-gaJpZM4JFuQW>
> .
>


-- 
"*Traveling upon the level of time to, that undiscovered country from whose
bourne no traveler returns.*"


Godfrey D. Beray

Cubeworks Technology Consulting & Solutions Inc. <http://cubeworks.com.ph/>
Senior Development Consultant


F&C Group of Companies <http://fncgroup.com.ph/>
Society Agri-Venture Enterprise <http://societyagri.com.ph/>
IT Consultant

+639189256321

**Comment by FNCGROUP** [comment]
sa payroll register computation? yes sir sakto man, galing nd ma identify
ni accounting kay gina recompute nila. p net na lang sang holiday pay sang
late/undertime.

Thank you,


Girlie E. Jamelo
Payroll Department
F & C GROUP OF COMPANIES
Guanco Street
Iloilo City, Philippines

**Comment by jetdario** [comment]
sa diin ni nga report? pdf or excel?

On Wednesday, 6 July 2016, FNCGROUP <notifications@github.com> wrote:

> sa payroll register computation? yes sir sakto man, galing nd ma identify
> ni accounting kay gina recompute nila. p net na lang sang holiday pay sang
> late/undertime.
>
> Thank you,
>
>
> Girlie E. Jamelo
> Payroll Department
> F & C GROUP OF COMPANIES
> Guanco Street
> Iloilo City, Philippines
>
> On Tue, Jul 5, 2016 at 7:31 PM, Jet Beray <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > pero sakto ang computation?
> >
> > On Wednesday, 6 July 2016, FNCGROUP <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > >
> > > - for Daily as of July 06, 2016 checking if my late or undertime,
> > > dapat my ma reflect nga late or undertime sa regular late/undertime
> > > equivalent of it.Then my late/undertime sa holiday late/undertime
> > > equivalent of it. paki net ang holiday pay sang late/undertime during
> > > holiday. kay indi ma tally pag gin compute ang excell, my naka hide nga
> > > deduction which is ang late/undertime during holiday.
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/jetdario/hrms/issues/31>, or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AGpj3ZjvhDdqhVLBEya43Yg-yYwEosk1ks5qSx_-gaJpZM4JFuQW
> > >
> > > .
> > >
> >
> >
> > --
> > "*Traveling upon the level of time to, that undiscovered country from
> whose
> > bourne no traveler returns.*"
> >
> >
> > Godfrey D. Beray
> >
> > Cubeworks Technology Consulting & Solutions Inc. <
> http://cubeworks.com.ph/
> > >
> > Senior Development Consultant
> >
> >
> > F&C Group of Companies <http://fncgroup.com.ph/>
> > Society Agri-Venture Enterprise <http://societyagri.com.ph/>
> > IT Consultant
> >
> > +639189256321
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/jetdario/hrms/issues/31#issuecomment-230662907>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AQxd_5S4ZZ69EAyCTpSxw77ywTXqXaEGks5qSyGAgaJpZM4JFuQW
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jetdario/hrms/issues/31#issuecomment-230663198>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGpj3QfBwA9hCNzaiJrwMGINQ6WvmDyMks5qSyIXgaJpZM4JFuQW>
> .
>


-- 
"*Traveling upon the level of time to, that undiscovered country from whose
bourne no traveler returns.*"


Godfrey D. Beray

Cubeworks Technology Consulting & Solutions Inc. <http://cubeworks.com.ph/>
Senior Development Consultant


F&C Group of Companies <http://fncgroup.com.ph/>
Society Agri-Venture Enterprise <http://societyagri.com.ph/>
IT Consultant

+639189256321

**Comment by FNCGROUP** [comment]
pareho sir, pa net sa PDF kag Excell report.

Thank you,


Girlie E. Jamelo
Payroll Department
F & C GROUP OF COMPANIES
Guanco Street
Iloilo City, Philippines
