### ISSUE TITLE
withholding tax march 2016

### ISSUE THREAD

**Issue by FNCGROUP** [jetdario/hrms#8]
-sir, ang gina generate sa PDF report ok siya na basis, pero ang gna export sa excell lain. dapat same sila gina kwaan nga data sa PDF.
- ang gina kwaan sa gna export to excell naga base sa payroll register.

*pdf report hindi complete name ang g gwa, like:
- favorite pizzas - ayala center cebu only ayala center ang g gwa sa report-ok 4/6/16
- favorite fastfood - robinsons galleria only robinsons g gwa sa report-ok 4/6/16
- favorite fastfood - sm city cebu foodcourt only sm city cebu g gwa sa report-ok 4/6/16

_**- favorite fastfood - sm city iloilo foodhall, boracay Big Italian ang g gwa sa pdf dapat favorite italian        fastfood-
- favorite fastfood  - sm naga ang branch name nga reflect sta lucia pero tama ang employee list na gna tag ya. tpus aNG heading ya sala dpat fasfood indi fresh italian serving****
- _

**Comment by jetdario** [comment]
@FNCGROUP : ready for review.

**Comment by FNCGROUP** [comment]
-no changes

**Comment by FNCGROUP** [comment]
- ang gina generate sa excel indi pareho sa PDF report. over all property ang naga guwa sa report. indi per branch. ok man tani nga over all galing kulang ang gina pick up nga list sang employees.
